# Assignment 1: Numpy

Perform the follwing tasks:


In [79]:
#3.1: import the numpy library
import numpy as np

In [106]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
np.shape(A)

(10, 10)

In [107]:
range(0,np.shape(A)[0],1)

range(0, 10)

In [108]:
A


array([[0.09214463, 0.39725606, 0.51547704, 0.72208577, 0.06281507,
        0.23975465, 0.2733142 , 0.18325468, 0.95714546, 0.74651217],
       [0.95147717, 0.41201478, 0.61925912, 0.31263589, 0.51013755,
        0.9339497 , 0.43057794, 0.01155602, 0.46466014, 0.47023685],
       [0.19571366, 0.28678673, 0.32923801, 0.42152136, 0.51745798,
        0.7080942 , 0.64997067, 0.55073909, 0.6522988 , 0.86298679],
       [0.91079056, 0.67488555, 0.07456851, 0.37019984, 0.70836982,
        0.04648088, 0.1477804 , 0.22622454, 0.24874438, 0.13523084],
       [0.70896214, 0.47741543, 0.80703704, 0.47274893, 0.15345958,
        0.98794759, 0.77276242, 0.89798947, 0.15689252, 0.01129232],
       [0.19769879, 0.36052278, 0.45670218, 0.08686436, 0.82929714,
        0.79146113, 0.09220248, 0.00326723, 0.14934475, 0.03340018],
       [0.53951637, 0.47996142, 0.7621385 , 0.60517088, 0.25322326,
        0.09020003, 0.75374054, 0.59968196, 0.75553036, 0.02503906],
       [0.9425036 , 0.95137314, 0.2559537

In [109]:
#3.3: return only the odd rows of A
B=np.array([])
for row in range(0,np.shape(A)[0],1):
    if (row%2==1):
        if np.size(B) == 0:
            B=np.array([A[row,:]])
        else:
            B = np.concatenate((B,[A[row,:]]),axis=0)
print(B)
np.shape(B)

[[0.95147717 0.41201478 0.61925912 0.31263589 0.51013755 0.9339497
  0.43057794 0.01155602 0.46466014 0.47023685]
 [0.91079056 0.67488555 0.07456851 0.37019984 0.70836982 0.04648088
  0.1477804  0.22622454 0.24874438 0.13523084]
 [0.19769879 0.36052278 0.45670218 0.08686436 0.82929714 0.79146113
  0.09220248 0.00326723 0.14934475 0.03340018]
 [0.9425036  0.95137314 0.25595378 0.66179445 0.92657034 0.17449087
  0.07008906 0.9476483  0.35464471 0.92759004]
 [0.10284095 0.39256791 0.52411991 0.5939466  0.8822165  0.28396937
  0.05568351 0.44682301 0.29972404 0.1798772 ]]


(5, 10)

In [110]:
#3.4: perform a matrix multiplication of A with it's transposed
B = np.matrix(A)
C = B*B.T
np.shape(B)

(10, 10)

In [111]:
#3.5: compute the matrix inverse of A
A_inv = np.linalg.inv(A)

In [116]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask = ((A > 0.5)-1)*(-0.5)+0.5
print(mask)
D = A *mask
print(D)



[[1.  1.  0.5 0.5 1.  1.  1.  1.  0.5 0.5]
 [0.5 1.  0.5 1.  0.5 0.5 1.  1.  1.  1. ]
 [1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 1.  1.  0.5 1.  1.  1.  1.  1. ]
 [0.5 1.  0.5 1.  1.  0.5 0.5 0.5 1.  1. ]
 [1.  1.  1.  1.  0.5 0.5 1.  1.  1.  1. ]
 [0.5 1.  0.5 0.5 1.  1.  0.5 0.5 0.5 1. ]
 [0.5 0.5 1.  0.5 0.5 1.  1.  0.5 1.  0.5]
 [0.5 1.  0.5 1.  1.  0.5 0.5 1.  0.5 0.5]
 [1.  1.  0.5 0.5 0.5 1.  1.  1.  1.  1. ]]
[[0.09214463 0.39725606 0.25773852 0.36104289 0.06281507 0.23975465
  0.2733142  0.18325468 0.47857273 0.37325608]
 [0.47573859 0.41201478 0.30962956 0.31263589 0.25506878 0.46697485
  0.43057794 0.01155602 0.46466014 0.47023685]
 [0.19571366 0.28678673 0.32923801 0.42152136 0.25872899 0.3540471
  0.32498533 0.27536955 0.3261494  0.4314934 ]
 [0.45539528 0.33744278 0.07456851 0.37019984 0.35418491 0.04648088
  0.1477804  0.22622454 0.24874438 0.13523084]
 [0.35448107 0.47741543 0.40351852 0.47274893 0.15345958 0.49397379
  0.38638121 0.44899474 0.15689252 0.01129

In [125]:
#Alternative
A = np.random.rand(10,10)
print(A[0,:])
A[np.where(A>0.5)] = A[np.where(A>0.5)]/2
print(A[0,:])

[0.49675164 0.10003451 0.52052466 0.84209948 0.37516705 0.90964958
 0.53842769 0.91276945 0.50015933 0.47662428]
[0.49675164 0.10003451 0.26026233 0.42104974 0.37516705 0.45482479
 0.26921384 0.45638472 0.25007966 0.47662428]
