# Assignment 1: Numpy

Perform the follwing tasks:


In [3]:
#3.1: import the numpy library
import numpy as np

In [15]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
np.shape(A)

(10, 10)

In [16]:
#3.3: return only the odd rows of A
B=np.array([])
for row in range(0,np.shape(A)[0],1):
    if (row%2==1):
        if np.size(B) == 0:
            B=np.array([A[row,:]])
        else:
            B = np.concatenate((B,[A[row,:]]),axis=0)
print(B)
np.shape(B)

[[0.77970951 0.40302175 0.32384706 0.30891685 0.02715657 0.40428858
  0.58327953 0.61213403 0.05853632 0.92681344]
 [0.97603443 0.68788844 0.82296516 0.64065942 0.82156841 0.50863506
  0.69865525 0.46486716 0.74025469 0.77221963]
 [0.12121861 0.87187103 0.66141316 0.95069241 0.5306668  0.31798134
  0.35943518 0.61748438 0.57676263 0.61298435]
 [0.99517353 0.24539986 0.38652561 0.91599054 0.99951236 0.54357614
  0.12901238 0.15364315 0.87535516 0.47386434]
 [0.1513731  0.48240704 0.57177806 0.7973855  0.0435721  0.51415032
  0.65948698 0.31112191 0.39797458 0.0752427 ]]


(5, 10)

In [17]:
#3.4: perform a matrix multiplication of A with it's transposed
B = np.matrix(A)
C = B*B.T
np.shape(B)

(10, 10)

In [18]:
#3.5: compute the matrix inverse of A
A_inv = np.linalg.inv(A)

In [19]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask = ((A > 0.5)-1)*(-0.5)+0.5
print(mask)
D = A *mask
print(D)



[[0.5 0.5 0.5 1.  1.  0.5 1.  0.5 0.5 0.5]
 [0.5 1.  1.  1.  1.  1.  0.5 0.5 1.  0.5]
 [1.  0.5 0.5 1.  0.5 1.  0.5 0.5 1.  0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.  0.5 0.5]
 [1.  0.5 1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  0.5 0.5 0.5 0.5 1.  1.  0.5 0.5 0.5]
 [0.5 0.5 1.  0.5 1.  1.  1.  0.5 0.5 1. ]
 [0.5 1.  1.  0.5 0.5 0.5 1.  1.  0.5 1. ]
 [1.  1.  0.5 1.  0.5 0.5 0.5 0.5 0.5 0.5]
 [1.  1.  0.5 0.5 1.  0.5 0.5 1.  1.  1. ]]
[[0.37034923 0.47618628 0.26725962 0.41261272 0.29608176 0.32083817
  0.38061766 0.31668383 0.35563475 0.27163951]
 [0.38985476 0.40302175 0.32384706 0.30891685 0.02715657 0.40428858
  0.29163976 0.30606701 0.05853632 0.46340672]
 [0.45158736 0.31835356 0.29503205 0.0199616  0.42257666 0.45771435
  0.31626053 0.3091096  0.21256979 0.35683338]
 [0.48801722 0.34394422 0.41148258 0.32032971 0.4107842  0.25431753
  0.34932762 0.46486716 0.37012734 0.38610981]
 [0.19414231 0.31296895 0.39117799 0.31137167 0.30219765 0.04021519
  0.35343293 0.42288187 0.02183675 0.2316

In [20]:
#Alternative
A = np.random.rand(10,10)
print(A[0,:])
A[np.where(A>0.5)] = A[np.where(A>0.5)]/2
print(A[0,:])

[0.2649737  0.92165253 0.35764309 0.86223952 0.77361949 0.28242792
 0.52669701 0.04167095 0.29339037 0.22343774]
[0.2649737  0.46082627 0.35764309 0.43111976 0.38680974 0.28242792
 0.26334851 0.04167095 0.29339037 0.22343774]
